# SPFx Extensions
# Master ID: #296
site_name: SharePoint Framework Client-Side Extension Samples
#theme: readthedocs
plugins:
    - macros
    - markdownextradata
    - redirects:
        redirect_maps:
          'samples/type.md': 'index.md'
nav:
  # - Home: index.md
  - Samples:
    - By Extension Type: index.md
    - By Framework: samples/framework.md
    - By SPFx Version: samples/spfx.md
  - Getting Started:
    - Using the Samples: gettingstarted/index.md
  # - Tutorials: 
  #   - Tutorials: tutorials/index.md
  - Contributing:
    - Contribution Guide: contributing/index.md
    - Submitting an Issue or Suggestion: contributing/issues.md
    - Forking?: contributing/forking.md
    - Submitting a Pull Request: contributing/pullrequest.md
theme:
  name: 'material'
  custom_dir: 'custom_theme'
  palette:
    primary: 'pnp'
    accent: 'indigo'
  logo: 'img/pnp-samples-white.svg'
  icon:
  repo: 'fontawesome/brands/git-alt'
  feature:
    tabs: true
extra_css:
  - 'css/site.css'
  - 'css/extra.css'
  - 'css/filter.css'
  - 'https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.0.0/css/fabric.min.css'
extra_javascript:
  - 'https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js'
  - 'https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js'
  - 'javascript/isotope.pkgd.min.js'
  - 'javascript/loadsamples.js'
  - 'javascript/filtersamples.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  telemetry: 'telemetry.sharepointpnp.com/sp-dev-fx-extensions'
  twitter_site: '@m365pnp'
  media_url: https://github.com/pnp/sp-dev-fx-extensions/img/pnp-samples-white.png
  twitter_media_url: https://pnp.github.io/sp-dev-fx-extensions/img/pnp-samples-logo-twitter.png
  media_alt: Patterns and Practices Samples
  site_search_url: https://pnp.github.io/sp-dev-fx-extensions/?query=
  version: '1.0.0-0'
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/m365pnp'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/playlist?list=PLR9nK3mnD-OXgMjDBdjWUTRia89oixBhx'
    - icon: 'fontawesome/solid/link'
      link: 'https://aka.ms/m365pnp'
repo_url: https://github.com/pnp/sp-dev-fx-extensions
edit_uri: tree/Docs/docs
site_url: https://pnp.github.io/sp-dev-fx-extensions/
site_favicon: favicon.ico